export const FETCH_LIST = "planet/FETCH_LIST";
export const FETCH_LIST_COMPLETED = "planet/FETCH_LIST_COMPLETED";
export const FETCH_LIST_FAILED = "planet/FETCH_LIST_FAILED";
export const FETCH_PLANET_COMPLETED = "FETCH_PLANET_COMPLETED";
export const FETCH_PLANET = "FETCH_PLANET";
